apiVersion: v1
kind: Service
metadata:
  name: python-app-clusterip
spec:
  type: ClusterIP
  selector:
    app: python-app # Adjust the selector to match your deployment labels
  ports:
    - port: 80
      targetPort: 5000 # Adjust if your app listens on a different port
