apiVersion: v1
kind: Service
metadata:
  name: python-app-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: python-app # Ensure this matches your deployment's labels
  ports:
    - port: 80
      targetPort: 5000
