apiVersion: v1
kind: Service
metadata:
  name: python-app-nodeport
spec:
  type: NodePort
  selector:
    app: python-app # Assuming your deployment has this label
  ports:
    - port: 80
      targetPort: 5000 # Assuming your app is running on this port inside the container
      nodePort: 30007 # Optional: specify a port or let Kubernetes choose
